package com.bluemethod.jabs.jabs.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * Represents a User, stored in the table user
 */
@Entity
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id; //ID is generated by SQL

    private String username; //Display name for identification
    private String steamID; //If used, the player's SteamID

    public User() { }

    public User(String username, String steamID)
    {
        this.setUsername(username);
        this.setSteamID(steamID);
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getSteamID() {
        return steamID;
    }

    public void setSteamID(String steamID) {
        this.steamID = steamID;
    }

    @Override
    public String toString()
    {
        return "User{id=" + getId() + ", username=" + getUsername() + ", steamID=" + getSteamID() + "}";
    }
}
